# Generated by Django 3.0.6 on 2021-05-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTimezones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('timezone1', models.CharField(blank=True, max_length=100)),
                ('timezone2', models.CharField(blank=True, max_length=100)),
                ('timezone3', models.CharField(blank=True, max_length=100)),
                ('timezone4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('acknowledge', models.BooleanField(default=False)),
                ('date_str', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_manager', models.DateTimeField(blank=True, null=True)),
                ('seen_unseen', models.BooleanField(default=False)),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=False)),
                ('normal_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email2', models.CharField(blank=True, max_length=100)),
                ('phone_no_1', models.CharField(blank=True, max_length=100)),
                ('phone_no_2', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('count_timer', models.CharField(blank=True, max_length=100)),
                ('it_equipment_specification', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('add_schedule_date_time', models.CharField(blank=True, max_length=100)),
                ('last_countdown_timer_time', models.DateTimeField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('profile_pic', models.FileField(blank=True, default='/static/img/admin-demo.png', null=True, upload_to='')),
                ('last_location', models.CharField(blank=True, max_length=200)),
                ('date_company_join', models.DateTimeField(blank=True, null=True)),
                ('date_department_join', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.Departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, null=True)),
                ('acknowledge', models.BooleanField(default=False)),
                ('seen_unseen', models.BooleanField(default=False)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.TaskModel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_staff', models.DateTimeField(blank=True, null=True)),
                ('created_manager', models.DateTimeField(blank=True, null=True)),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('online_time', models.IntegerField(blank=True, default=0, null=True)),
                ('offline_time', models.IntegerField(blank=True, default=0, null=True)),
                ('break_time', models.IntegerField(blank=True, default=0, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('login_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('weekday', models.CharField(blank=True, max_length=12, null=True)),
                ('iso_weekday', models.IntegerField(blank=True, null=True)),
                ('day_off', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.ScheduleTime')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name_by_user', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('doc', models.BooleanField(default=False)),
                ('docx', models.BooleanField(default=False)),
                ('pdf', models.BooleanField(default=False)),
                ('ppt', models.BooleanField(default=False)),
                ('csv', models.BooleanField(default=False)),
                ('jpeg', models.BooleanField(default=False)),
                ('xls', models.BooleanField(default=False)),
                ('pptx', models.BooleanField(default=False)),
                ('xlsx', models.BooleanField(default=False)),
                ('jpg', models.BooleanField(default=False)),
                ('png', models.BooleanField(default=False)),
                ('mp4', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_am_here', models.BooleanField(default=False)),
                ('in_meeting', models.BooleanField(default=False)),
                ('lunch_break', models.BooleanField(default=False)),
                ('tea_break', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('greek_o_msg', models.TextField(blank=True, null=True)),
                ('notification', models.TextField(blank=True, null=True)),
                ('notification_type', models.TextField(blank=True, null=True)),
                ('additional_msg', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.FileField(blank=True, default='/static/img/admin-demo.png', null=True, upload_to='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.Departments')),
                ('manaager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('descrtiption', models.TextField(blank=True, null=True)),
                ('to_email', models.CharField(blank=True, max_length=250, null=True)),
                ('from_email', models.CharField(blank=True, max_length=250, null=True)),
                ('to_name', models.CharField(blank=True, max_length=250, null=True)),
                ('from_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_staff', models.DateTimeField(blank=True, null=True)),
                ('created_manager', models.DateTimeField(blank=True, null=True)),
                ('seen_unseen', models.BooleanField(default=False)),
                ('email_reply', models.TextField(blank=True, null=True)),
                ('date_str', models.CharField(blank=True, max_length=30, null=True)),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EailReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reply', models.TextField(blank=True, null=True)),
                ('email_reply_time', models.DateTimeField(blank=True, null=True)),
                ('email_reply_time_staff', models.DateTimeField(blank=True, null=True)),
                ('emailobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.EmailModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('seen_unseen', models.BooleanField(default=False)),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_updated_receiver', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('archive_2', models.BooleanField(default=False)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_1', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_receiver', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.ChatThread')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.Departments')),
                ('resource_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.SavedDocumentModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normal_user.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('alert_message', models.TextField(blank=True, null=True)),
                ('seen_unseen', models.BooleanField(default=False)),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
