# Generated by Django 3.0.6 on 2021-05-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0003_chatmodel_chatroom_reportfilter_testmodelnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='tbl_user',
        ),
    ]
