# Generated by Django 3.0.6 on 2021-05-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0004_auto_20210527_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={},
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table=None,
        ),
    ]
