# Generated by Django 3.0.6 on 2021-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0005_auto_20210528_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='complete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
