# Generated by Django 3.0.6 on 2021-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0006_taskmodel_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='complete',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='complete_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
