"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import pymysql

pymysql.install_as_MySQLdb()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@w8!48*s3yiwtc*ipdxkw9ltbg1&186mtmb!ibe4996q-yyr5('

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'normal_user',
    'captcha',
    'channels',
    'admin_app',
    'channels_redis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'
ASGI_APPLICATION = "mysite.routing.application"
# CITIES_COUNTRY_MODEL = 'normal_user.CustomCountryModel'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'mysite.wsgi.application'

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"
# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'screenmonitors',
        'USER': 'sammy',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }
}

DEFAULT_CHARSET = 'utf-8'
# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGES = [
    ("en-us",("English")),
    ("el",("Greek"))
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = False

USE_TZ = True



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
       
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

if not DEBUG:
    STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "admin"),
    )

    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
else:
     
    STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "admin"),
    os.path.join(BASE_DIR, 'static'),
    )



STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR,'MEDIA')
MEDIA_URL = "/MEDIA/"
MEDIA_NEW_URL = "/MEDIA/"
DEFAULT_STORAGE = "/home/tchubadm1n/public_html/mysite/MEDIA"
PROFILE_IMAGE_PATH = "/home/tchubadm1n/public_html/mysite/static/profile_pictures/" # create profile_pictures directory first
REPORTING_CSVS = "/home/tchubadm1n/public_html/mysite/static/reporting_csvs/" # create reporting_csvs directory first


#SOCKET_URL = "wss://teamconnecthub.net"

# SOCKET_URL = "ws://http://192.168.42.221/:9001"

#POPUP_URL = "https://teamconnecthub.net/"
# POPUP_URL = "http://192.168.42.221/:9001"



SOCKET_URL = "wss://teamconnecthub.net"
# SOCKET_URL = "ws://192.81.223.127:9001"
# 192.168.160.56

POPUP_URL = "https://teamconnecthub.net/"
# POPUP_URL = "http://192.81.223.127:9001/"

LOCALE_PATHS = [os.path.join(BASE_DIR,'locale')]
LOCALE_PATHS = [os.path.join(BASE_DIR,'locale')]

